#!/bin/sh -e
#
# $Id$
# Copyright (C) 2003  Dmitry V. Levin <ldv@altlinux.org>
# 
# The hsh utility for the hasher project
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

hasher_dir=/usr/share/hasher
. $hasher_dir/functions

Usage()
{
	cat >&2 <<EOF
hsh - builds package using hasher utilities.

This program is free software, covered by the GNU General Public License.
mkchroot comes with ABSOLUTELY NO WARRANTY, see license for details.

Usage: $PROG [options] <path-to-workdir> <package>...

Valid options are:
--target=ARCH                   target architecture;
--number=NUMBER                 subconfig identifier;
--pkg-build-priv-dir=DIR        pkg-build-priv directory;
--contents-index-bin=INDEX      pkg contents binary index;
--contents-index-all=INDEX      pkg contents complete index;
-v, --verbose                   print a message for each action;
-h, --help                      show this text.
EOF
	[ -n "$1" ] && exit "$1" || exit
}

TEMP=`getopt -n $PROG -o v,h -l target:,number:,pkg-build-priv-dir:,contents-index-all:,contents-index-bin:,verbose,help -- "$@"` || Usage
eval set -- "$TEMP"

contents_index_all=
contents_index_bin=
while :; do
	case "$1" in
		--target) shift; target="$1"; shift
			;;
		--number)
			shift
			number="$1"
			[ -z "$(echo -E "$number" |tr -d [0-9])" ] ||
				Fatal "$number: invalid number."
			number="-$number"
			shift
			;;
		--pkg-build-priv-dir) shift; pkg_build_priv_dir="$1"; shift
			;;
		--contents-index-all) shift; contents_index_all="$1"; shift
			;;
		--contents-index-bin) shift; contents_index_bin="$1"; shift
			;;
		-v|--verbose) verbose=-v; shift
			;;
		-h|--help) Usage 0
			;;
		--) shift; break
			;;
		*) Fatal "unrecognized option: $1"
			;;
	esac
done

# At least two arguments, please.
[ "$#" -ge 2 ] || Usage
set_workdir "$1"
shift

for f in "$@"; do
	rm -rf aptbox
	$hasher_dir/mkaptbox "$workdir" -u \
			${verbose:+$verbose} \
			#
	[ ! -d chroot ] ||
		$hasher_dir/rmchroot "$workdir" \
			${verbose:+$verbose} \
			${number:+$number} \
			--pkg-build-priv-dir="$pkg_build_priv_dir" \
			#
	$hasher_dir/mkchroot "$workdir" \
			${verbose:+$verbose} \
			${number:+$number} \
			--pkg-build-priv-dir="$pkg_build_priv_dir" \
			#
	$hasher_dir/initroot "$workdir" \
			${verbose:+$verbose} \
			${number:+$number} \
			--pkg-build-priv-dir="$pkg_build_priv_dir" \
			${contents_index_all:+--contents-index-all=$contents_index_all} \
			${contents_index_bin:+--contents-index-all=$contents_index_bin} \
			#
	$hasher_dir/rebuild "$workdir" \
			${verbose:+$verbose} \
			${number:+$number} \
			--pkg-build-priv-dir="$pkg_build_priv_dir" \
			--target="$target" \
			"$f"
done
