#!/bin/sh -e
#
# $Id$
# Copyright (C) 2003-2005  Dmitry V. Levin <ldv@altlinux.org>
# 
# The mkaptbox utility for the hasher project
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

if [ "$0" = ./mkaptbox ]; then
	. ./functions
	hasher_dir="$(/bin/pwd)"
else
	. /usr/share/hasher/functions
fi

Usage()
{
	[ "$1" = 0 ] || exec >&2
	cat <<EOF
mkaptbox - creates initial aptbox in specified working directory.

Usage: $PROG [options] <path-to-workdir>

<path-to-workdir> must be valid writable directory.

Valid options are:
  --with-stuff              configure sources.list for the work repository;
  --without-stuff           do not configure sources.list for the work repository;
  --target=ARCH             target architecture of the work repository;
  --repo=DIR                path to work repository directory;
  --apt-config=FILE         path to custom apt.conf file;
  --apt-prefix=DIR          path to apt directory prefix (e.g. /usr);
  --no-update               do not run "apt-get update" after creation;
  -u, --update              run "apt-get update" after creation;
  -f, --force               force aptbox creation;
  -q, --quiet               try to be more quiet;
  -v, --verbose             print a message for each action;
  -V, --version             print program version and exit;
  -h, --help                show this text and exit.

Report bugs to http://bugs.altlinux.ru/

EOF
	[ -n "$1" ] && exit "$1" || exit
}

TEMP=`getopt -n $PROG -o f,u,q,v,V,h -l with-stuff,without-stuff,no-stuff,target:,repo:,apt-config:,apt-prefix:,no-update,update,force,quiet,verbose,help,version -- "$@"` || Usage
eval set -- "$TEMP"

force=
update=1
apt_config=
while :; do
	case "$1" in
		--with-stuff) no_stuff=
			;;
		--without-stuff|--no-stuff) no_stuff=1
			;;
		--target) shift; target="$1"
			[ -z "${target##[A-Za-z]*}" ] ||
				Fatal "--target: $target: invalid architecture."
			;;
		--repo) shift; repo="$1"
			;;
		--apt-config)
			apt_config="$(opt_check_read "$1" "$2")"
			shift
			;;
		--apt-prefix)
			apt_prefix="$(opt_check_dir "$1" "$2")"
			shift
			;;
		--no-update) update=
			;;
		-u|--update) update=1
			;;
		-f|--force) force=1
			;;
		-q|--quiet) quiet=-q
			;;
		-v|--verbose) verbose=-v
			;;
		-V|--version) print_version mkaptbox
			;;
		-h|--help) Usage 0
			;;
		--) shift; break
			;;
		*) Fatal "unrecognized option: $1"
			;;
	esac
	shift
done

# Exactly one argument, please.
[ "$#" -eq 1 ] || Usage
set_workdir "$1"
shift

set_apt_vars
make_repo
update_repo

# exists already?
if [ -e aptbox -o -L aptbox ]; then
	[ -n "$force" ] || Fatal "remove $aptbox first."
	[ -d aptbox ] || Fatal "$aptbox: invalid pathname."

	# empty dir?
	if rmdir -- aptbox 2>/dev/null; then
		mkdir -m700 $verbose -- aptbox
		cd aptbox
	else
		cd aptbox
		[ -d ./etc/apt -a -d ./var/lib/rpm ] ||
			Fatal "$aptbox: doesn't look valid."
	fi
else
	mkdir -m700 $verbose -- aptbox
	cd aptbox
fi

Verbose "changed working directory to \`$aptbox'"

# apt/rpm skeleton directories.
mkdir -p $verbose -- \
	./etc/apt/{apt.conf,{sources,vendors}.list}.d \
	./var/cache/apt/archives/partial \
	./var/lib/apt/lists/partial \
	./var/lib/rpm

[ -z "$apt_config" ] || APT_CONFIG="$apt_config"

read_apt_config Dir::Etc::SourceList sl_value

# reset APT_CONFIG and fill it with new data.
export APT_CONFIG="$aptbox/etc/apt/apt.conf"
cat >"$APT_CONFIG" <<__EOF__
${apt_config:+$(cat "$apt_config")}
Dir::State "$aptbox/var/lib/apt/";
Dir::Cache "$aptbox/var/cache/apt/";
Dir::Etc::SourceList "$aptbox/etc/apt/sources.list";
RPM::RootDir "$aptbox";
APT::Install::Virtual "true";
APT::Install::VirtualVersion "true";
__EOF__
Verbose "created APT configuration file \`$APT_CONFIG'"

target_config="./etc/apt/sources.list"
cat >"$target_config" <<__EOF__
${no_stuff:+#}rpm file:$workdir/${repo:-$def_repo} ${target:-$def_target} hasher
$(grep '^[^#]' "$sl_value")
__EOF__
Verbose "created APT source list file \`$target_config'"

# create a new rpm database.
rpmdb --initdb --dbpath "$aptbox/var/lib/rpm"
Verbose "created RPM database in \`./var/lib/rpm/'"

# create apt wrappers.
for n in apt-cache apt-config apt-get genbasedir; do
	cat >"$n" <<__EOF__
#!/bin/sh -e

if [ -n "$LD_LIBRARY_PATH" ]; then
	LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
	export LD_LIBRARY_PATH
fi
APT_CONFIG="$APT_CONFIG" \
exec $(eval printf %s "$(printf '$prog_%s' "$n" |tr - _)") "\$@"
__EOF__
Verbose "created $n wrapper"
chmod $verbose a+x "$n"
done

[ -z "$update" ] || "$prog_apt_get" update $([ -n "$verbose" ] || echo -qq)
