#!/bin/sh -e
#
# $Id$
# Copyright (C) 2003  Dmitry V. Levin <ldv@altlinux.org>
# 
# The rmchroot utility for the hasher project
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

. /usr/share/hasher/functions

Usage()
{
	cat >&2 <<EOF
rmchroot - removes chroot created by mkchroot.

This program is free software, covered by the GNU General Public License.
rmchroot comes with ABSOLUTELY NO WARRANTY, see license for details.

Usage: $PROG [options] <path-to-workdir>

Valid options are:
--number=NUMBER                 subconfig identifier;
--pkg-build-priv-dir=DIR        pkg-build-priv directory;
-v, --verbose                   print a message for each action;
-h, --help                      show this text.
EOF
	[ -n "$1" ] && exit "$1" || exit
}

TEMP=`getopt -n $PROG -o v,h -l number:,pkg-build-priv-dir:,verbose,help -- "$@"` || Usage
eval set -- "$TEMP"

while :; do
	case "$1" in
		--number)
			shift
			number="$1"
			[ -z "$(echo -E "$number" |tr -d [0-9])" ] ||
				Fatal "--number: $number: invalid number."
			number="-$number"
			shift
			;;
		--pkg-build-priv-dir) shift; pkg_build_priv_dir="$1"; shift
			;;
		-v|--verbose) verbose=-v; shift
			;;
		-h|--help) Usage 0
			;;
		--) shift; break
			;;
		*) Fatal "unrecognized option: $1"
			;;
	esac
done

# exactly one argument, please.
[ "$#" -eq 1 ] || Usage
set_workdir "$1"
shift

check_helpers

cd chroot
Verbose "changed working directory to \`$chroot'"

for n in .host/{sh,rm} dev/null; do
	[ -e "./$n" ] || Fatal "cannot find ./$n file."
done

cat >.host/entry <<\__EOF__
#!/.host/sh
chmod -Rf u+rwX -- /* 2>/dev/null
/.host/rm -rf -- /*/ 2>/dev/null
exit 0
__EOF__
chmod 755 .host/entry

"$chrootuid2" $number "$chroot" /.host/entry &&
	Verbose "removed files owned by user2" ||
	Fatal "chrootuid2 failed."

"$chrootuid1" $number "$chroot" /.host/entry &&
	Verbose "removed files owned by user1" ||
	Fatal "chrootuid1 failed."

rm -rf $verbose -- "$chroot" ||
	Fatal "failed to remove some files."
