#!/bin/sh -ef
#
# Copyright (C) 2003-2006  Dmitry V. Levin <ldv@altlinux.org>
# 
# The mkaptbox utility for the hasher project
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
#

hasher_dir="$(dirname "$0")"
[ -r "$hasher_dir/functions" ] &&
	hasher_dir="$(readlink -env "$hasher_dir")" ||
	hasher_dir="/usr/share/hasher"
. "$hasher_dir/functions"

show_help()
{
	cat <<EOF
mkaptbox - create initial aptbox in specified working directory.

Usage: $PROG [options] <path-to-workdir>

<path-to-workdir> must be valid writable directory.

Options:
  --apt-config=FILE         path to custom apt.conf file;
  --apt-prefix=DIR          path to apt directory prefix (e.g. /usr);
  -f, --force               force aptbox creation;
  --no-update               do not run "apt-get update" after creation;
  --repo=DIR                path to work repository directory;
  --repo-bin=DIR            binary packages destination directory,
                            overriding --repo option for binary packages;
  --repo-src=DIR            source packages destination directory,
                            overriding --repo option for source packages;
  --target=ARCH             target architecture of the work repository;
  -u, --update              run "apt-get update" after creation;
  --without-stuff           do not configure sources.list for the work repository;
  --with-stuff              configure sources.list for the work repository;
  -q, --quiet               try to be more quiet;
  -v, --verbose             print a message for each action;
  -V, --version             print program version and exit;
  -h, --help                show this text and exit.

Report bugs to http://bugs.altlinux.ru/

EOF
	exit
}

TEMP=`getopt -n $PROG -o f,u,h,q,v,V -l apt-config:,apt-prefix:,force,no-stuff,no-update,repo:,repo-bin:,repo-src:,target:,update,without-stuff,with-stuff,help,quiet,verbose,version -- "$@"` ||
	show_usage
eval set -- "$TEMP"

force=
update=1
while :; do
	case "$1" in
		--apt-config)
			apt_config="$(opt_check_read "$1" "$2")"
			shift
			;;
		--apt-prefix)
			apt_prefix="$(opt_check_dir "$1" "$2")"
			shift
			;;
		-f|--force) force=1
			;;
		--no-update) update=
			;;
		--repo) shift; repo="$1"
			;;
		--repo-bin) shift; repo_bin="$1"
			;;
		--repo-src) shift; repo_src="$1"
			;;
		--target) shift; target="$1"
			[ -z "${target##[A-Za-z]*}" ] ||
				Fatal "--target: $target: invalid architecture."
			;;
		-u|--update) update=1
			;;
		--without-stuff|--no-stuff) no_stuff=1
			;;
		--with-stuff) no_stuff=
			;;
		--) shift; break
			;;
		*) parse_common_options mkaptbox "$1"
			;;
	esac
	shift
done

# Exactly one argument, please.
[ "$#" -ge 1 ] || show_usage 'Insufficient arguments.'
[ "$#" -le 1 ] || show_usage 'Too many arguments.'

set_workdir "$1"
shift

# does aptbox exist yet?
if [ -e aptbox -o -L aptbox ]; then
	[ -n "$force" ] || Fatal "remove $aptbox first."
	[ -d aptbox ] || Fatal "$aptbox: invalid pathname."

	# empty dir?
	if rmdir -- aptbox 2>/dev/null; then
		mkdir -m700 $verbose -- aptbox
		cd aptbox
	else
		cd aptbox
		[ -d ./etc/apt -a -d ./var/lib/rpm ] ||
			Fatal "$aptbox: doesn't look valid."
	fi
else
	mkdir -m700 $verbose -- aptbox
	cd aptbox
fi

Verbose "Changed working directory to \`$aptbox'."

# create apt/rpm skeleton directories.
mkdir -p $verbose -- \
	./etc/apt/{apt.conf,{sources,vendors}.list}.d \
	./home/user \
	./var/cache/apt/archives/partial \
	./var/lib/apt/lists/partial \
	./var/lib/rpm

# define apt variables.
prog_apt_get="apt-get"
prog_apt_cache="apt-cache"
prog_apt_config="apt-config"
prog_genbasedir="genbasedir"
apt_libdir=
if [ -z "$apt_prefix" ]; then
	apt_libdir="$LD_LIBRARY_PATH"
else
	[ -d "$apt_prefix" ] ||
		Fatal "$apt_prefix: directory not available."

	if printf %s "$apt_prefix" |grep -qs '[`"$\]'; then
		Fatal "$apt_prefix: illegal symbols in apt prefix."
	fi

	apt_libdir="$apt_prefix/lib"
	[ -d "$apt_libdir" ] ||
		Fatal "$apt_libdir: directory not available."

	if [ -n "$LD_LIBRARY_PATH" ]; then
		apt_libdir="$LD_LIBRARY_PATH:$apt_libdir"
	fi

	for n in apt-cache apt-config apt-get genbasedir; do
		prog="$apt_prefix/bin/$n"
		[ -x "$prog" ] ||
			Fatal "$prog: program not available."
		var="$(printf '$prog_%s' "$n" |tr - _)"
		eval "$var=\"$(quote_arg "$prog")\""
	done
fi
if printf %s "$apt_libdir" |grep -qs '[`"$\]'; then
	Fatal "$LD_LIBRARY_PATH: illegal symbols in LD_LIBRARY_PATH."
fi

# create aptbox version of ~/.rpmrc if necessary.
aptbox_home=
rpm_showrc="$(rpm --showrc)"
current_arch="$(printf %s "$rpm_showrc" |sed -ne 's/^install arch[[:space:]]*:[[:space:]]*\([^[:space:]]\+\).*/\1/p')"
[ -n "$current_arch" ] ||
	current_arch="$(uname -m)"
if [ "$current_arch" != "${target:-$def_target}" ] &&
   ! printf %s "$rpm_showrc" |
     grep -qs "^compatible archs[[:space:]]*:.*\<${target:-$def_target}\>"; then
	aptbox_home="$aptbox/home/user"
	for f in "$HOME/.rpmrc" "$HOME/.rpmmacros"; do
		[ ! -f "$f" ] ||
			install -pm600 $verbose -- "$f" "$aptbox_home/"
	done
	echo "arch_compat: $current_arch: ${target:-$def_target}" >> "$aptbox_home/.rpmrc"
fi

# create apt wrappers.
apt_config_file="$aptbox/etc/apt/apt.conf"
for n in apt-cache apt-config apt-get genbasedir; do
	cat >"$n" <<__EOF__
#!/bin/sh -e
${apt_libdir:+export LD_LIBRARY_PATH="$apt_libdir"}
APT_CONFIG="$apt_config_file" \
${aptbox_home:+HOME="$aptbox_home"} \
exec $(eval printf %s "$(printf '$prog_%s' "$n" |tr - _)") "\$@"
__EOF__
	Verbose "created $n wrapper"
	chmod $verbose a+x "$n"
done

cat >regenbasedir <<__EOF__
#!/bin/sh -ef
"$aptbox/genbasedir" --topdir="$workdir/${repo:-$def_repo}" --no-oldhashfile --bz2only --mapi ${target:-$def_target} hasher "\$@"
"$aptbox/apt-get" ${quiet:+-qq} update
__EOF__
Verbose "created regenbasedir"
chmod $verbose a+x regenbasedir

# create initial apt.conf file.
cat >"$apt_config_file" <<__EOF__
${apt_config:+$(cat "$apt_config")}
__EOF__

read_apt_config Dir::Etc::SourceList sl_value

# create final apt.conf file.
cat >"$apt_config_file" <<__EOF__
Dir::State "$aptbox/var/lib/apt/";
Dir::Cache "$aptbox/var/cache/apt/";
${apt_config:+$(cat "$apt_config")}
Dir::Etc::SourceList "$aptbox/etc/apt/sources.list";
RPM::RootDir "$aptbox";
APT::Install::Virtual "true";
APT::Install::VirtualVersion "true";
__EOF__
Verbose "Created APT configuration file \`$apt_config_file'."

# create a new sources.list file.
target_config="./etc/apt/sources.list"
cat >"$target_config" <<__EOF__
${no_stuff:+#}rpm file:$workdir/${repo:-$def_repo} ${target:-$def_target} hasher
$(grep '^[^#]' "$sl_value")
__EOF__
Verbose "Created APT source list file \`$target_config'."

# create a new rpm database.
rpmdb --initdb --dbpath "$aptbox/var/lib/rpm"
Verbose "Created RPM database in \`./var/lib/rpm/'."

cd "$workdir"
make_repo
update_repo
[ -z "$update" ] || "$aptbox/apt-get" update $([ -n "$verbose" ] || echo -qq)
